CREATE TABLE barbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL
);

CREATE TABLE barber_availabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_barber_availabilities_barber
        FOREIGN KEY (barber_id) REFERENCES barbers (id),
    CONSTRAINT chk_barber_availabilities_day_of_week
        CHECK (day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )),
    CONSTRAINT chk_barber_availabilities_time_range
        CHECK (start_time < end_time)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_appointments_barber
        FOREIGN KEY (barber_id) REFERENCES barbers (id),
    CONSTRAINT fk_appointments_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_appointments_status
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELED')),
    CONSTRAINT chk_appointments_time_range
        CHECK (start_time < end_time)
);

CREATE INDEX idx_barber_availabilities_barber_day
    ON barber_availabilities (barber_id, day_of_week);

CREATE INDEX idx_appointments_barber_start_end
    ON appointments (barber_id, start_time, end_time);

CREATE INDEX idx_appointments_customer
    ON appointments (customer_id);
